export type Book = {
    year: string
    title: string
    author: string
    audiobook: boolean
}

export const books: Book[] = [
    {
        year: '2026',
        title: 'Hot Lights, Cold Steel: Life, Death and Sleepless Nights in a Surgeon’s First Years',
        author: 'Michael J. Collins, MD',
        audiobook: false,
    },
    {
        year: '2026',
        title: 'The Mountain Between Us',
        author: 'Charles Martin',
        audiobook: true,
    },
    {
        year: '2026',
        title: 'The Redemption of Time: A Three-Body Problem Novel',
        author: 'Baoshu',
        audiobook: true,
    },
    {
        year: '2026',
        title: 'Blue Collar, Blue Scrubs: The Making of a Surgeon',
        author: 'Michael J. Collins, MD',
        audiobook: false,
    },
    {
        year: '2026',
        title: 'Death’s End',
        author: 'Cixin Liu',
        audiobook: true,
    },
    {
        year: '2026',
        title: 'The Dark Forest',
        author: 'Cixin Liu',
        audiobook: true,
    },
    {
        year: '2026',
        title: 'Crazy Love: Overwhelmed by a Relentless God',
        author: 'Francis Chan',
        audiobook: false,
    },
    {
        year: '2026',
        title: 'The Good Life Method: Reasoning Through the Big Questions of Happiness, Faith, and Meaning',
        author: 'Meghan Sullivan and Paul Blaschko',
        audiobook: true,
    },
    {
        year: '2026',
        title: 'White Oleander',
        author: 'Janet Fitch',
        audiobook: true,
    },
    {
        year: '2026',
        title: 'The Three-Body Problem',
        author: 'Cixin Liu',
        audiobook: true,
    },
    {
        year: '2026',
        title: 'Spirit-Controlled Temperament',
        author: 'Tim LaHaye',
        audiobook: false,
    },
    {
        year: '2026',
        title: 'Leave the World Behind',
        author: 'Rumaan Alam',
        audiobook: true,
    },
    {
        year: '2026',
        title: 'Malibu Rising',
        author: 'Taylor Jenkins Reid',
        audiobook: true,
    },
    {
        year: '2026',
        title: 'The Anxious Generation: How the Great Rewiring of Childhood Is Causing an Epidemic of Mental Illness',
        author: 'Jonathan Haidt',
        audiobook: true,
    },
    {
        year: '2026',
        title: 'No More Mr. Nice Guy: A Proven Plan For Getting What You Want In Love, Sex, And Life',
        author: 'Robert A. Glover',
        audiobook: true,
    },
    {
        year: '2026',
        title: 'Murder in Mesopotamia',
        author: 'Agatha Christie',
        audiobook: false,
    },
    {
        year: '2026',
        title: 'The Darkest White: A Mountain Legend and the Avalanche That Took Him',
        author: 'Eric Blehm',
        audiobook: false,
    },
    {
        year: '2026',
        title: 'Freakonomics: A Rogue Economist Explores the Hidden Side of Everything',
        author: 'Steven Levitt and Stephen J. Dubner',
        audiobook: true,
    },
    {
        year: '2025',
        title: 'Player Piano',
        author: 'Kurt Vonnegut',
        audiobook: false,
    },
    {
        year: '2025',
        title: 'The Last Blue Mountain: The Great Karakoram Climbing Tragedy',
        author: 'Ralph Barker',
        audiobook: false,
    },
    {
        year: '2025',
        title: 'Ready Player Two',
        author: 'Ernest Cline',
        audiobook: false,
    },
    {
        year: '2025',
        title: 'Lolita',
        author: 'Vladimir Nabokov',
        audiobook: true,
    },
    {
        year: '2025',
        title: 'Fire Weather: The Making of a Beast',
        author: 'John Vaillant',
        audiobook: false,
    },
    {
        year: '2025',
        title: 'The Color of Everything: A Journey to Quiet the Chaos Within',
        author: 'Cory Richards',
        audiobook: false,
    },
    {
        year: '2025',
        title: 'Atomic Habits: An Easy & Proven Way to Build Good Habits & Break Bad Ones',
        author: 'James Clear',
        audiobook: false,
    },
    {
        year: '2025',
        title: 'Anxious for Nothing: Finding Calm in a Chaotic World',
        author: 'Max Lucado',
        audiobook: true,
    },
    {
        year: '2025',
        title: 'Try Softer: A Fresh Approach to Move Us out of Anxiety, Stress, and Survival Mode—and into a Life of Connection and Joy',
        author: 'Aundi Kolber',
        audiobook: false,
    },
    {
        year: '2025',
        title: 'How to Win Over Depression',
        author: 'Tim LaHaye',
        audiobook: false,
    },
    {
        year: '2025',
        title: 'Where the Crawdads Sing',
        author: 'Delia Owens',
        audiobook: false,
    },
    {
        year: '2025',
        title: 'Extreme Ownership: How U.S. Navy SEALs Lead and Win',
        author: 'Jocko Willink and Leif Babin',
        audiobook: true,
    },
    {
        year: '2025',
        title: '12 Rules for Life: An Antidote to Chaos',
        author: 'Jordan B. Peterson',
        audiobook: true,
    },
    {
        year: '2025',
        title: 'God on Mute: Engaging the Silence of Unanswered Prayer',
        author: 'Pete Greig',
        audiobook: true,
    },
    {
        year: '2025',
        title: 'Brain Energy: A Revolutionary Breakthrough in Understanding Mental Health--and Improving Treatment for Anxiety, Depression, OCD, PTSD, and More',
        author: 'Christopher M. Palmer, MD',
        audiobook: true,
    },
    {
        year: '2025',
        title: 'The Year of Less',
        author: 'Cait Flanders',
        audiobook: true,
    },
    {
        year: '2025',
        title: 'Dream Big: Know What You Want, Why You Want It, and What You’re Going to Do About It',
        author: 'Bob Goff',
        audiobook: false,
    },
    {
        year: '2025',
        title: 'Eight Dates: Essential Conversations for a Lifetime of Love',
        author: 'John Gottman, PhD and Julie Schwartz Gottman, PhD, Doug Abrams and Rachel Carlton Abrams, MD',
        audiobook: false,
    },
    {
        year: '2024',
        title: 'All the Light We Cannot See',
        author: 'Anthony Doerr',
        audiobook: false,
    },
    {
        year: '2024',
        title: 'An Unquiet Mind',
        author: 'Kay Redfield Jamison',
        audiobook: false,
    },
    {
        year: '2024',
        title: 'The Subtle Art of Not Giving a F*ck: A Counterintuitive Approach to Living a Good Life',
        author: 'Mark Manson',
        audiobook: false,
    },
    {
        year: '2024',
        title: 'The Meaning of Marriage: Facing the Complexities of Commitment with the Wisdom of God',
        author: 'Timothy Keller',
        audiobook: false,
    },
    {
        year: '2024',
        title: 'The Year of Living Biblically: One Man’s Humble Quest to follow the Bible as Literally as Possible',
        author: 'A.J. Jacobs',
        audiobook: false,
    },
    {
        year: '2024',
        title: 'Love Does: Discover a Secretly Incredible Life in an Ordinary World',
        author: 'Bob Goff',
        audiobook: false,
    },
    {
        year: '2024',
        title: 'My Dark Vanessa',
        author: 'Kate Elizabeth Russell',
        audiobook: false,
    },
    {
        year: '2024',
        title: 'Undistracted: Capture Your Purpose. Rediscover Your Joy.',
        author: 'Bob Goff',
        audiobook: false,
    },
    {
        year: '2024',
        title: 'The Golden Spruce: A True Story of Myth, Madness, And Greed',
        author: 'John Vaillant',
        audiobook: false,
    },
    {
        year: '2024',
        title: 'Scattered Minds: The Origins and Healing of Attention Deficit Disorder',
        author: 'Gabor Maté',
        audiobook: false,
    },
    {
        year: '2024',
        title: 'Everybody, Always: Becoming Love in a World Full of Setbacks and Difficult People',
        author: 'Bob Goff',
        audiobook: false,
    },
    {
        year: '2024',
        title: 'The Essex Serpent',
        author: 'Sarah Perry',
        audiobook: false,
    },
    {
        year: '2024',
        title: 'One Hundred Years of Solitude',
        author: 'Gabriel García Márquez',
        audiobook: false,
    },
    {
        year: '2024',
        title: 'The Ruthless Elimination of Hurry: How to Stay Emotionally Healthy and Spiritually Alive in the Chaos of the Modern World',
        author: 'John Mark Comer',
        audiobook: false,
    },
    {
        year: '2024',
        title: 'I Don’t Want to Talk About It: Overcoming the Secret Legacy of Male Depression',
        author: 'Terrence Real',
        audiobook: false,
    },
    {
        year: '2024',
        title: 'Outlive: The Science & Art of Longevity',
        author: 'Peter Attia, MD',
        audiobook: false,
    },
    {
        year: '2024',
        title: 'Ministries of Mercy: The Call of the Jericho Road',
        author: 'Timothy Keller',
        audiobook: false,
    },
    {
        year: '2023',
        title: 'It',
        author: 'Stephen King',
        audiobook: false,
    },
    {
        year: '2023',
        title: 'Breathless',
        author: 'Amy McCulloch',
        audiobook: false,
    },
    {
        year: '2023',
        title: 'Structured Chaos: The unusual life of a climber',
        author: 'Victor Saunders',
        audiobook: false,
    },
    {
        year: '2023',
        title: 'Prayer: Does It Make Any Difference?',
        author: 'Philip Yancey',
        audiobook: false,
    },
    {
        year: '2023',
        title: 'The Dharma Bums',
        author: 'Jack Kerouac',
        audiobook: false,
    },
    {
        year: '2023',
        title: 'Barbarian Days: A Surfing Life',
        author: 'William Finnegan',
        audiobook: false,
    },
    {
        year: '2023',
        title: 'Where the Clouds Can Go',
        author: 'Conrad Kain',
        audiobook: false,
    },
    {
        year: '2023',
        title: 'Native Air',
        author: 'Jonathan Howland',
        audiobook: false,
    },
    {
        year: '2023',
        title: 'The Metamorphosis',
        author: 'Franz Kafka',
        audiobook: false,
    },
    {
        year: '2023',
        title: 'Human Traces',
        author: 'Sebastian Faulks',
        audiobook: false,
    },
    {
        year: '2022',
        title: 'The Secret Agent',
        author: 'Joseph Conrad',
        audiobook: false,
    },
    {
        year: '2022',
        title: 'Ridgerunner',
        author: 'Gil Adamson',
        audiobook: false,
    },
    {
        year: '2022',
        title: 'What God Has to Say about Our Bodies: How the Gospel Is Good News for Our Physical Selves',
        author: 'Sam Allberry',
        audiobook: false,
    },
    {
        year: '2022',
        title: 'Countdown to Zero Day: Stuxnet and the Launch of the World’s First Digital Weapon',
        author: 'Kim Zetter',
        audiobook: false,
    },
    {
        year: '2022',
        title: 'The Death of Ivan Ilyich',
        author: 'Leo Tolstoy',
        audiobook: false,
    },
    {
        year: '2022',
        title: 'One Green Bottle',
        author: 'Elizabeth Coxhead',
        audiobook: false,
    },
    {
        year: '2022',
        title: 'Brave New World Revisited',
        author: 'Aldous Huxley',
        audiobook: false,
    },
    {
        year: '2022',
        title: 'Brave New World',
        author: 'Aldous Huxley',
        audiobook: false,
    },
    {
        year: '2021',
        title: 'The Runaway Jury',
        author: 'John Grisham',
        audiobook: false,
    },
    {
        year: '2021',
        title: 'Uncanny Valley',
        author: 'Anna Wiener',
        audiobook: false,
    },
    {
        year: '2021',
        title: 'The Firm',
        author: 'John Grisham',
        audiobook: false,
    },
    {
        year: '2021',
        title: 'The Mosquito Coast',
        author: 'Paul Theroux',
        audiobook: false,
    },
    {
        year: '2021',
        title: 'Fearfully and Wonderfully Made',
        author: 'Dr. Paul Brand and Philip Yancey',
        audiobook: false,
    },
    {
        year: '2021',
        title: 'Carrie',
        author: 'Stephen King',
        audiobook: false,
    },
    {
        year: '2021',
        title: 'The Stand: The Complete & Uncut Edition',
        author: 'Stephen King',
        audiobook: false,
    },
    {
        year: '2021',
        title: '50 Percent of Mountaineering is Uphill',
        author: 'Susanna Pfisterer',
        audiobook: false,
    },
    {
        year: '2021',
        title: 'The Pilgrim’s Progress',
        author: 'John Bunyan',
        audiobook: false,
    },
    {
        year: '2021',
        title: 'McTeague',
        author: 'Frank Norris',
        audiobook: false,
    },
    {
        year: '2021',
        title: 'On Writing: A Memoir of the Craft',
        author: 'Stephen King',
        audiobook: false,
    },
    {
        year: '2021',
        title: 'The Body: A Guide for Occupants',
        author: 'Bill Bryson',
        audiobook: false,
    },
    {
        year: '2020',
        title: 'Anna Karenin',
        author: 'Leo Tolstoy, translated by Rosemary Edmonds',
        audiobook: false,
    },
    {
        year: '2020',
        title: 'Reminiscences of a Stock Operator',
        author: 'Edwin Lefèvre',
        audiobook: false,
    },
    {
        year: '2020',
        title: 'At Home in Nature',
        author: 'Rob Wood',
        audiobook: false,
    },
    {
        year: '2020',
        title: 'This Is Depression: A Comprehensive, Compassionate Guide for Anyone Who Wants to Understand Depression',
        author: 'Diane McIntosh',
        audiobook: false,
    },
    {
        year: '2020',
        title: 'The Question of God: C.S. Lewis and Sigmund Freud Debate God, Love, Sex, and the Meaning of Life',
        author: 'Armand Nicholi',
        audiobook: false,
    },
    {
        year: '2020',
        title: 'Famous Last Words',
        author: 'Timothy Findley',
        audiobook: false,
    },
    {
        year: '2019',
        title: 'South',
        author: 'Ernest Shackleton',
        audiobook: false,
    },
    {
        year: '2019',
        title: 'Little Fires Everywhere',
        author: 'Celeste Ng',
        audiobook: false,
    },
    {
        year: '2019',
        title: 'Educated',
        author: 'Tara Westover',
        audiobook: false,
    },
    {
        year: '2019',
        title: 'Amusing Ourselves to Death: Public Discourse in the Age of Show Business',
        author: 'Neil Postman',
        audiobook: false,
    },
    {
        year: '2019',
        title: 'Beyond the Mountain',
        author: 'Steve House',
        audiobook: false,
    },
    {
        year: '2019',
        title: 'Echoes: One Climber’s Hard Road to Freedom',
        author: 'Nick Bullock',
        audiobook: false,
    },
    {
        year: '2018',
        title: 'Ready Player One',
        author: 'Ernest Cline',
        audiobook: false,
    },
    {
        year: '2018',
        title: 'Crazy Rich Asians',
        author: 'Kevin Kwan',
        audiobook: false,
    },
    {
        year: '2018',
        title: 'China Rich Girlfriend',
        author: 'Kevin Kwan',
        audiobook: false,
    },
    {
        year: '2018',
        title: 'Rich People Problems',
        author: 'Kevin Kwan',
        audiobook: false,
    },
    {
        year: '2018',
        title: 'The Bold and Cold: A History of 25 Classic Climbs in the Canadian Rockies',
        author: 'Brandon Pullan',
        audiobook: false,
    },
    {
        year: '2018',
        title: 'Art of Freedom: The Life and Climbs of Voytek Kurtyka',
        author: 'Bernadette McDonald',
        audiobook: false,
    },
    {
        year: '2018',
        title: 'Autonomy, Mastery and Purpose in the Avalanche Patch',
        author: 'Bruce Kay',
        audiobook: false,
    },
    {
        year: '2018',
        title: 'Mountains in My Heart: A Passion for Climbing',
        author: 'Gerlinde Kaltenbrunner',
        audiobook: false,
    },
    {
        year: '2018',
        title: 'A Purpose Ridden',
        author: 'Ryan Correy',
        audiobook: false,
    },
    {
        year: '2018',
        title: 'Modern Romance',
        author: 'Aziz Ansari',
        audiobook: false,
    },
    {
        year: '2018',
        title: 'How to Win Friends and Influence People',
        author: 'Dale Carnegie',
        audiobook: false,
    },
    {
        year: '2018',
        title: 'Radical',
        author: 'David Platt',
        audiobook: false,
    },
    {
        year: '2018',
        title: 'The 10 Best Decisions a Man Can Make: The Adventure of living in God’s Plan',
        author: 'Bill Farrel',
        audiobook: false,
    },
    {
        year: '2018',
        title: 'Soul Surviver: How my Faith Survived the Church',
        author: 'Philip Yancey',
        audiobook: false,
    },
    {
        year: '2017',
        title: 'The Reason for God: Belief in an Age of Skepticism',
        author: 'Timothy Keller',
        audiobook: false,
    },
    {
        year: '2017',
        title: 'Mere Christianity',
        author: 'C.S. Lewis',
        audiobook: false,
    },
    {
        year: '2017',
        title: 'The Case for a Creator',
        author: 'Lee Strobel',
        audiobook: false,
    },
    {
        year: '2017',
        title: 'The Case for Faith',
        author: 'Lee Strobel',
        audiobook: false,
    },
    {
        year: '2017',
        title: 'Disappointment with God',
        author: 'Philip Yancey',
        audiobook: false,
    },
    {
        year: '2017',
        title: 'What’s So Amazing About Grace?',
        author: 'Philip Yancey',
        audiobook: false,
    },
    {
        year: '2017',
        title: 'Who Moved the Stone?',
        author: 'Frank Morison',
        audiobook: false,
    },
    {
        year: '2017',
        title: 'The Real Face of Atheism',
        author: 'Ravi Zacharias',
        audiobook: false,
    },
    {
        year: '2017',
        title: 'The Problem of God',
        author: 'Mark Clark',
        audiobook: false,
    },
    {
        year: '2017',
        title: 'Orthodoxy',
        author: 'Gilbert Keith Chesterton',
        audiobook: false,
    },
    {
        year: '2016',
        title: 'I Hope They Serve Beer in Hell',
        author: 'Tucker Max',
        audiobook: false,
    },
    {
        year: '2016',
        title: 'Sloppy Seconds',
        author: 'Tucker Max',
        audiobook: false,
    },
    {
        year: '2016',
        title: 'Hilarity Ensues',
        author: 'Tucker Max',
        audiobook: false,
    },
    {
        year: '2016',
        title: 'Flash Boys: A Wall Street Revolt',
        author: 'Michael Lewis',
        audiobook: false,
    },
    {
        year: '2016',
        title: 'When Breath Becomes Air',
        author: 'Paul Kalanithi',
        audiobook: false,
    },
    {
        year: '2016',
        title: 'Better: A Surgeon’s Notes on Performance',
        author: 'Atul Gawande',
        audiobook: false,
    },
    {
        year: '2016',
        title: 'Being Mortal',
        author: 'Atul Gawande',
        audiobook: false,
    },
    {
        year: '2016',
        title: 'The Checklist Manifesto',
        author: 'Atul Gawande',
        audiobook: false,
    },
    {
        year: '2016',
        title: 'One Day in the Life of Ivan Denisovich',
        author: 'Aleksandr Solzhenitsyn',
        audiobook: false,
    },
    {
        year: '2015',
        title: 'Summit Fever. The Story of an Armchair Climber on the 1984 Mustagh Tower Expedition',
        author: 'Andrew Greig',
        audiobook: false,
    },
    {
        year: '2014',
        title: 'The Calling: A Life Rocked by Mountains',
        author: 'Barry Blanchard',
        audiobook: false,
    },
    {
        year: '2014',
        title: 'One Day as a Tiger: Alex Macintyre and the Birth of Light and Fast Alpinism',
        author: 'John Porter',
        audiobook: false,
    },
    {
        year: '2014',
        title: 'K2: Life and Death on the World’s Most Dangerous Mountain',
        author: 'Ed Viesturs',
        audiobook: false,
    },
    {
        year: '2014',
        title: 'Annapurna: First Conquest of an 8000-meter Peak',
        author: 'Maurice Herzog',
        audiobook: false,
    },
    {
        year: '2014',
        title: 'The Great Gatsby',
        author: 'F. Scott Fitzgerald',
        audiobook: false,
    },
    {
        year: '2013',
        title: 'Doctor Sleep',
        author: 'Stephen King',
        audiobook: false,
    },
    {
        year: '2013',
        title: 'The Will to Climb: Obsession and Commitment and the Quest to Climb Annapurna—the World’s Deadliest Peak',
        author: 'Ed Viesturs',
        audiobook: false,
    },
    {
        year: '2012',
        title: 'No Shortcuts to the Top: Climbing the World’s 14 Highest Peaks',
        author: 'Ed Viesturs',
        audiobook: false,
    },
    {
        year: '2012',
        title: 'Sh*t My Dad Says',
        author: 'Justin Halpern',
        audiobook: false,
    },
    {
        year: '2012',
        title: 'I Suck at Girls',
        author: 'Justin Halpern',
        audiobook: false,
    },
    {
        year: 'Earlier',
        title: 'Chickenhawk',
        author: 'Robert Mason',
        audiobook: false,
    },
    {
        year: 'Earlier',
        title: 'Dune',
        author: 'Frank Herbert',
        audiobook: false,
    },
    {
        year: 'Earlier',
        title: 'Ender’s Game',
        author: 'Orson Scott Card',
        audiobook: false,
    },
    {
        year: 'Earlier',
        title: 'Nineteen Eighty-Four',
        author: 'George Orwell',
        audiobook: false,
    },
    {
        year: 'Earlier',
        title: 'Birdsong',
        author: 'Sebastian Faulks',
        audiobook: false,
    },
    {
        year: 'Earlier',
        title: 'Absolute Friends',
        author: 'John le Carré',
        audiobook: false,
    },
    {
        year: 'Earlier',
        title: 'The Guns of Navarone',
        author: 'Alistair MacLean',
        audiobook: false,
    },
    {
        year: 'Earlier',
        title: 'Z for Zachariah',
        author: 'Robert C. O’Brien',
        audiobook: false,
    },
    {
        year: 'Earlier',
        title: 'Dragonsbane',
        author: 'Barbara Hambly',
        audiobook: false,
    },
    {
        year: 'Earlier',
        title: 'The Hunt for Red October',
        author: 'Tom Clancy',
        audiobook: false,
    },
    {
        year: 'Earlier',
        title: 'Rite of Passage',
        author: 'Alexei Panshin',
        audiobook: false,
    },
    {
        year: 'Earlier',
        title: 'Fallen Angels',
        author: 'Walter Dean Myers',
        audiobook: false,
    },
    {
        year: 'Earlier',
        title: 'Deathwatch',
        author: 'Robb White',
        audiobook: false,
    },
]
