name: Run Cypress Tests
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    cypress-run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install modules
              run: npm ci
            - name: Cypress
              uses: cypress-io/github-action@v6
              with:
                  browser: chrome
                  headless: true
                  build: npm run build
                  start: npm run preview
                  wait-on: http://localhost:4000
                  wait-on-timeout: 60
              env:
                  VITE_IMAGEKIT_PRIVATE_KEY: ${{ secrets.VITE_IMAGEKIT_PRIVATE_KEY }}
                  VITE_IMAGEKIT_PUBLIC_KEY: ${{ secrets.VITE_IMAGEKIT_PUBLIC_KEY }}
                  VITE_IMAGEKIT_URL_ENDPOINT: ${{ secrets.VITE_IMAGEKIT_URL_ENDPOINT }}
